#!/usr/bin/env python3
"""Schedule 365 shorts — one per day for a year.

Usage:
    python scripts/schedule_365_shorts.py [--start-day 1] [--end-day 365]
    python scripts/schedule_365_shorts.py --single 1   # Just day 1

Runs the full pipeline for each day and uploads with scheduled publish date.
Cleans up temp files between each run. Tracks progress in shorts_tracker.csv.
"""

import argparse
import csv
import datetime
import logging
import shutil
import sys
import tempfile
import time
from pathlib import Path

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
logger = logging.getLogger("scheduler")

# Add core package to path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "packages" / "core" / "src"))


def get_themes_for_day(day: int) -> str:
    """Cycle through 4 themes deterministically."""
    themes = ["solar_flare", "oceanic_tones", "urban_decay", "neon_dusk"]
    return themes[(day - 1) % len(themes)]


def run_day(
    day: int,
    cookies_path: str = "cookies_kingofdub.txt",
    work_dir: str = "/tmp/openmusic_365",
    dry_run: bool = False,
    no_upload: bool = False,
    backend: str = "youtube-up",
) -> str:
    """Generate, upload, and schedule a single day's short.

    Args:
        day: Day number (1-365).
        cookies_path: Path to cookies.txt.
        work_dir: Working directory for temp files.
        dry_run: Skip actual generation/upload.

    Returns:
        True if successful.
    """
    from openmusic.shorts.quotes import get_quote_for_day
    from openmusic.shorts.pipeline import ShortsPipeline, ShortConfig
    from openmusic.shorts.renderer import ShortsRenderer
    from openmusic.export.youtube_uploader import YouTubeUploader, YouTubeUploadConfig
    from openmusic.export.yt_upload_backend import YtUploadConfig, upload_video as yt_upload_video

    work_path = Path(work_dir)
    work_path.mkdir(parents=True, exist_ok=True)

    # Calculate scheduled publish date
    today = datetime.date.today()
    publish_date = today + datetime.timedelta(days=day)
    publish_datetime = datetime.datetime(
        publish_date.year, publish_date.month, publish_date.day,
        hour=12, minute=0, second=0,  # Noon publish
    )

    # Get deterministic quote for this day
    quote = get_quote_for_day(day)
    theme = get_themes_for_day(day)

    logger.info(f"=== Day {day}/365 | Theme: {theme} | Publish: {publish_date} ===")
    logger.info(f"Quote: {quote.text[:80]}... — {quote.author}")

    if dry_run:
        logger.info(f"[DRY RUN] Would generate & upload for day {day}")
        return True

    # ── Step 1: Generate audio via ACE-Step ──
    output_path = str(work_path / f"short_day{day}.mp4")

    # We'll generate audio on the fly using --generate-audio approach
    from openmusic.acestep.generator import ACEStepGenerator

    generator = ACEStepGenerator()
    logger.info("Generating 30s audio via ACE-Step...")
    wav_path = generator.generate_texture(
        prompt="deep meditative dub techno texture",
        duration=30,
        bpm=120 + (day % 20),  # Vary bpm slightly: 120-139
        key=["Dm", "Cm", "Am", "Fm", "Gm", "Em"][day % 6],
    )
    logger.info(f"Audio generated: {wav_path}")

    # ── Step 2: Render short ──
    logger.info("Rendering short via Playwright...")
    renderer = ShortsRenderer(width=1080, height=1920)
    pipeline = ShortsPipeline(renderer=renderer)

    config = ShortConfig(
        quote=quote,
        audio_path=str(wav_path),
        audio_start_time=0,
        clip_duration=30,
        output_path=output_path,
        portrait=True,
        theme=theme,
        tags=["stoic", "dub techno", "philosophy", "daily wisdom", "openmusic"],
    )

    result = pipeline.generate_short(config)
    logger.info(f"Short rendered: {result}")

    # Clean up audio temp file
    try:
        Path(wav_path).unlink()
    except Exception:
        pass

    # ── Step 3: Upload with scheduled publish ──
    if no_upload:
        logger.info(f"Skipping upload for day {day} (--no-upload)")
        return f"local_{day}"

    logger.info("Uploading to YouTube with scheduled publish...")

    # Description varies by day
    month_names = ["January", "February", "March", "April", "May", "June",
                   "July", "August", "September", "October", "November", "December"]
    description = (
        f"☯ Daily Stoic — Day {day} of 365\n\n"
        f"\"{quote.text}\"\n"
        f"— {quote.author}\n\n"
        f"Generated by OpenMusic — AI-powered dub techno & stoic wisdom.\n"
        f"https://github.com/tobias-weiss-ai-xr/openmusic\n\n"
        f"#{quote.author.replace(' ', '')} #Stoicism #DailyStoic #DubTechno #OpenMusic"
    )

    if backend == "yt-upload":
        video_id = yt_upload_video(
            video_path=result,
            title=f"Daily Stoic — Day {day}: {quote.author}",
            description=description,
            privacy="public",
            scheduled_publish=publish_datetime,
            tags=["stoic", "dub techno", "philosophy", "daily wisdom", "openmusic"],
        )
        # yt-upload returns full URL, extract ID
        if "watch?v=" in video_id:
            video_id = video_id.split("watch?v=")[-1]
        logger.info(f"Uploaded: https://youtube.com/watch?v={video_id}")
    else:
        uploader = YouTubeUploader(config=YouTubeUploadConfig(
            title=f"Daily Stoic — Day {day}: {quote.author}",
            description=description,
            tags=["stoic", "dub techno", "philosophy", "daily wisdom", "openmusic"],
            cookies_file=cookies_path,
            playlist_title="Daily Stoic 365",
            privacy="public",
            scheduled_upload=publish_datetime,
        ))
        video_id = uploader.upload(result)
        logger.info(f"Uploaded: https://youtube.com/watch?v={video_id}")

    # ── Step 4: Cleanup ──
    try:
        Path(result).unlink()
        logger.info(f"Cleaned up: {result}")
    except Exception:
        pass

    return video_id


def load_tracker(tracker_path: str) -> set[int]:
    """Load already-completed days."""
    completed = set()
    try:
        with open(tracker_path, "r") as f:
            reader = csv.reader(f)
            next(reader, None)  # skip header
            for row in reader:
                if row:
                    completed.add(int(row[0]))
    except FileNotFoundError:
        pass
    return completed


def save_tracker(tracker_path: str, day: int, video_id: str, publish_date: str) -> None:
    """Record a completed day."""
    file_exists = Path(tracker_path).exists()
    with open(tracker_path, "a", newline="") as f:
        writer = csv.writer(f)
        if not file_exists:
            writer.writerow(["day", "video_id", "publish_date", "timestamp"])
        writer.writerow([day, video_id, publish_date, datetime.datetime.now().isoformat()])


def main():
    parser = argparse.ArgumentParser(description="Schedule 365 daily stoic shorts")
    parser.add_argument("--start-day", type=int, default=1, help="First day to process")
    parser.add_argument("--end-day", type=int, default=365, help="Last day to process")
    parser.add_argument("--single", type=int, default=None, help="Process a single day")
    parser.add_argument("--cookies", default="cookies_kingofdub.txt", help="Path to cookies.txt")
    parser.add_argument("--dry-run", action="store_true", help="Skip actual generation/upload")
    parser.add_argument("--no-upload", action="store_true", help="Generate audio+video only, skip upload")
    parser.add_argument("--resume", action="store_true", help="Skip already-completed days")
    parser.add_argument("--delay", type=int, default=0, help="Delay between days in seconds")
    parser.add_argument(
        "--backend", choices=["youtube-up", "yt-upload"], default="youtube-up",
        help="Upload backend (default: youtube-up)",
    )
    args = parser.parse_args()

    tracker_path = "shorts_tracker.csv"
    completed = load_tracker(tracker_path) if args.resume else set()

    if args.single:
        days = [args.single]
    else:
        days = range(args.start_day, args.end_day + 1)

    for day in days:
        if day in completed:
            logger.info(f"Day {day} already completed, skipping (--resume)")
            continue

        try:
            video_id = run_day(
                day=day,
                cookies_path=args.cookies,
                dry_run=args.dry_run,
                no_upload=args.no_upload,
                backend=args.backend,
            )
            if video_id and not args.dry_run:
                publish_date = str(datetime.date.today() + datetime.timedelta(days=day))
                save_tracker(tracker_path, day, video_id, publish_date)
                logger.info(f"Day {day} completed successfully!")
        except Exception as e:
            logger.error(f"Day {day} FAILED: {e}")
            import traceback
            traceback.print_exc()
            logger.info("Continuing to next day...")
            time.sleep(5)

        if day != days[-1] and args.delay > 0:
            logger.info(f"Waiting {args.delay}s before next day...")
            time.sleep(args.delay)


if __name__ == "__main__":
    main()
